const sampleProducts = [
  {
    id: 1,
    category: "Dresses",
    name: "Summer Floral Dress",
    color: "Red",
    size: "Small",
    brand: "Nike",
    rating: 4.5,
    availability: "In Stock",
    discount: 10,
    price: 80,
  },
  {
    id: 2,
    category: "Shoes",
    name: "Running Shoes",
    color: "Blue",
    size: "Medium",
    brand: "Puma",
    rating: 3.8,
    availability: "Out of Stock",
    discount: 0,
    price: 60,
  },
  {
    id: 3,
    category: "Electronics",
    name: "Smartphone X",
    color: "Black",
    brand: "Apple",
    rating: 4.2,
    availability: "In Stock",
    discount: 15,
    price: 500,
  },
  {
    id: 4,
    category: "Dresses",
    name: "Elegant Evening Gown",
    color: "Black",
    size: "Large",
    brand: "Nike",
    rating: 4.8,
    availability: "In Stock",
    discount: 20,
    price: 120,
  },
  {
    id: 5,
    category: "Shoes",
    name: "Casual Sneakers",
    color: "White",
    size: "Medium",
    brand: "Puma",
    rating: 4.0,
    availability: "In Stock",
    discount: 5,
    price: 70,
  },
  {
    id: 6,
    category: "Electronics",
    name: "Wireless Headphones",
    color: "Gray",
    brand: "Sony",
    rating: 4.5,
    availability: "Out of Stock",
    discount: 10,
    price: 80,
  },
  {
    id: 7,
    category: "Dresses",
    name: "Boho Maxi Dress",
    color: "Blue",
    size: "Medium",
    brand: "Nike",
    rating: 4.3,
    availability: "In Stock",
    discount: 10,
    price: 90,
  },
  {
    id: 8,
    category: "Shoes",
    name: "High Heel Pumps",
    color: "Red",
    size: "Small",
    brand: "Puma",
    rating: 4.7,
    availability: "In Stock",
    discount: 15,
    price: 100,
  },
  {
    id: 9,
    category: "Electronics",
    name: "Laptop Pro",
    color: "Silver",
    brand: "Apple",
    rating: 4.9,
    availability: "In Stock",
    discount: 25,
    price: 1200,
  },
  {
    id: 10,
    category: "Dresses",
    name: "Spring Floral Dress",
    color: "Green",
    size: "Small",
    brand: "Nike",
    rating: 4.2,
    availability: "In Stock",
    discount: 5,
    price: 70,
  },
  {
    id: 11,
    category: "Shoes",
    name: "Running Shoes 2",
    color: "Black",
    size: "Medium",
    brand: "Puma",
    rating: 3.5,
    availability: "Out of Stock",
    discount: 0,
    price: 55,
  },
  {
    id: 12,
    category: "Electronics",
    name: "Smartphone Y",
    color: "Gold",
    brand: "Apple",
    rating: 4.7,
    availability: "In Stock",
    discount: 10,
    price: 600,
  },
  {
    id: 13,
    category: "Dresses",
    name: "Cocktail Party Dress",
    color: "Red",
    size: "Large",
    brand: "Nike",
    rating: 4.6,
    availability: "In Stock",
    discount: 15,
    price: 110,
  },
  {
    id: 14,
    category: "Shoes",
    name: "Sneakers 2",
    color: "Blue",
    size: "Medium",
    brand: "Puma",
    rating: 4.1,
    availability: "In Stock",
    discount: 8,
    price: 80,
  },
  {
    id: 15,
    category: "Electronics",
    name: "Noise-Canceling Earbuds",
    color: "Black",
    brand: "Sony",
    rating: 4.5,
    availability: "Out of Stock",
    discount: 12,
    price: 90,
  },
  {
    id: 16,
    category: "Dresses",
    name: "Vintage Lace Dress",
    color: "White",
    size: "Medium",
    brand: "Nike",
    rating: 4.8,
    availability: "In Stock",
    discount: 20,
    price: 150,
  },
  {
    id: 17,
    category: "Shoes",
    name: "Casual Sandals",
    color: "Brown",
    size: "Large",
    brand: "Puma",
    rating: 4.0,
    availability: "In Stock",
    discount: 5,
    price: 65,
  },
  {
    id: 18,
    category: "Electronics",
    name: "Tablet Lite",
    color: "Blue",
    brand: "Apple",
    rating: 4.3,
    availability: "In Stock",
    discount: 8,
    price: 300,
  },
  {
    id: 19,
    category: "Dresses",
    name: "Chic Midi Dress",
    color: "Black",
    size: "Small",
    brand: "Nike",
    rating: 4.9,
    availability: "In Stock",
    discount: 25,
    price: 130,
  },
  {
    id: 20,
    category: "Shoes",
    name: "Sporty Sneakers",
    color: "Red",
    size: "Medium",
    brand: "Puma",
    rating: 4.5,
    availability: "Out of Stock",
    discount: 15,
    price: 85,
  },
  {
    id: 21,
    category: "Electronics",
    name: "Smartwatch Pro",
    color: "Silver",
    brand: "Sony",
    rating: 4.7,
    availability: "In Stock",
    discount: 20,
    price: 250,
  },
  {
    id: 22,
    category: "Dresses",
    name: "Floral Wrap Dress",
    color: "Blue",
    size: "Large",
    brand: "Nike",
    rating: 4.4,
    availability: "In Stock",
    discount: 10,
    price: 95,
  },
  {
    id: 23,
    category: "Shoes",
    name: "Classic Loafers",
    color: "Brown",
    size: "Small",
    brand: "Puma",
    rating: 4.2,
    availability: "In Stock",
    discount: 5,
    price: 75,
  },
  {
    id: 24,
    category: "Electronics",
    name: "Bluetooth Speaker",
    color: "Black",
    brand: "Apple",
    rating: 4.6,
    availability: "Out of Stock",
    discount: 0,
    price: 50,
  },
  {
    id: 25,
    category: "Dresses",
    name: "Bohemian Maxi Dress",
    color: "Green",
    size: "Medium",
    brand: "Nike",
    rating: 4.1,
    availability: "In Stock",
    discount: 5,
    price: 85,
  },
  {
    id: 26,
    category: "Shoes",
    name: "High Heel Boots",
    color: "Black",
    size: "Large",
    brand: "Puma",
    rating: 4.8,
    availability: "In Stock",
    discount: 15,
    price: 110,
  },
  {
    id: 27,
    category: "Electronics",
    name: "Gaming Laptop",
    color: "Red",
    brand: "Apple",
    rating: 4.9,
    availability: "In Stock",
    discount: 25,
    price: 1500,
  },
  {
    id: 28,
    category: "Dresses",
    name: "Lace Wedding Gown",
    color: "White",
    size: "Small",
    brand: "Nike",
    rating: 4.7,
    availability: "In Stock",
    discount: 20,
    price: 200,
  },
  {
    id: 29,
    category: "Shoes",
    name: "Running Shoes 3",
    color: "Blue",
    size: "Medium",
    brand: "Puma",
    rating: 4.3,
    availability: "Out of Stock",
    discount: 10,
    price: 70,
  },
  {
    id: 30,
    category: "Electronics",
    name: "4K Smart TV",
    color: "Black",
    brand: "Sony",
    rating: 4.5,
    availability: "In Stock",
    discount: 12,
    price: 800,
  },
];
export default sampleProducts;
